trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:

# =============================
# BUILD
# =============================
- stage: Build
  displayName: Build Application

  jobs:
  - job: BuildJob

    steps:

    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '8.x'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: 'Testing'
      inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration Release'

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop



# =============================
# QA DEPLOYMENT
# =============================
- stage: DeployQA
  displayName: Deploy to QA
  dependsOn: Build
  jobs:
  - deployment: QADeploy
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'myservice-connection'
              appType: 'webApp'
              appName: 'aesazuredevopswiprotraningapp'
              deployToSlotOrASE: true
              resourceGroupName: 'WL_SL_User_185'
              slotName: 'staging-qa'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'